<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('contents')->delete();

        DB::table('contents')->insert([
            ['course_id' => 1, 'season' => 'ادبیات تعلیمی', 'content' => 'درس ۱', 'pageStart' => 1, 'pageEnd' => 17],
            ['course_id' => 1, 'season' => 'ادبیات تعلیمی', 'content' => 'درس ۲', 'pageStart' => 18, 'pageEnd' => 30],
            ['course_id' => 1, 'season' => 'ادبیات پایداری', 'content' => 'درس ۳', 'pageStart' => 31, 'pageEnd' => 36],
            ['course_id' => 1, 'season' => 'ادبیات پایداری', 'content' => 'درس ۴', 'pageStart' => 37, 'pageEnd' => 38],
            ['course_id' => 1, 'season' => 'ادبیات پایداری', 'content' => 'درس ۵', 'pageStart' => 39, 'pageEnd' => 46],
            ['course_id' => 1, 'season' => 'ادبیات غنایی', 'content' => 'درس ۶', 'pageStart' => 47, 'pageEnd' => 50],
            ['course_id' => 1, 'season' => 'ادبیات غنایی', 'content' => 'درس ۷', 'pageStart' => 51, 'pageEnd' => 58],
            ['course_id' => 1, 'season' => 'ادبیات سفر و زندگی', 'content' => 'درس ۸', 'pageStart' => 59, 'pageEnd' => 63],
            ['course_id' => 1, 'season' => 'ادبیات سفر و زندگی', 'content' => 'درس ۹', 'pageStart' => 64, 'pageEnd' => 74],
            ['course_id' => 1, 'season' => 'ادبیات انقلاب اسلامی', 'content' => 'درس ۱۰', 'pageStart' => 75, 'pageEnd' => 81],
            ['course_id' => 1, 'season' => 'ادبیات انقلاب اسلامی', 'content' => 'درس ۱۱', 'pageStart' => 82, 'pageEnd' => 94],
            ['course_id' => 1, 'season' => 'ادبیات حماسی', 'content' => 'درس ۱۲', 'pageStart' => 95, 'pageEnd' => 101],
            ['course_id' => 1, 'season' => 'ادبیات حماسی', 'content' => 'درس ۱۳', 'pageStart' => 102, 'pageEnd' => 112],
            ['course_id' => 1, 'season' => 'ادبیات داستانی', 'content' => 'درس ۱۴', 'pageStart' => 113, 'pageEnd' => 117],
            ['course_id' => 1, 'season' => 'ادبیات داستانی', 'content' => 'درس ۱۵', 'pageStart' => 118, 'pageEnd' => 119],
            ['course_id' => 1, 'season' => 'ادبیات داستانی', 'content' => 'درس ۱۶', 'pageStart' => 120, 'pageEnd' => 132],
            ['course_id' => 1, 'season' => 'ادبیات جهان', 'content' => 'درس ۱۷', 'pageStart' => 133, 'pageEnd' => 139],
            ['course_id' => 1, 'season' => 'ادبیات جهان', 'content' => 'درس ۱۸', 'pageStart' => 140, 'pageEnd' => 149],
            ['course_id' => 4, 'season' => 'الدرس الاول', 'content' => 'ذلک هو الله', 'pageStart' => 1, 'pageEnd' => 14],
            ['course_id' => 4, 'season' => 'الدرس الثانی', 'content' => 'المواعظ العددیه', 'pageStart' => 15, 'pageEnd' => 28],
            ['course_id' => 4, 'season' => 'الدرس الثالث', 'content' => 'مطر السمک', 'pageStart' => 29, 'pageEnd' => 46],
            ['course_id' => 4, 'season' => 'الدرس الرابع', 'content' => 'التعایش السلمی', 'pageStart' => 47, 'pageEnd' => 62],
            ['course_id' => 4, 'season' => 'الدرس الخامس', 'content' => 'هذا خلق الله', 'pageStart' => 63, 'pageEnd' => 78],
            ['course_id' => 4, 'season' => 'الدرس السادس', 'content' => 'ذوالقرنین', 'pageStart' => 79, 'pageEnd' => 90],
            ['course_id' => 4, 'season' => 'الدرس السابع', 'content' => 'یا من فی البحار عجائبه', 'pageStart' => 91, 'pageEnd' => 106],
            ['course_id' => 4, 'season' => 'الدرس الثامن', 'content' => 'صناعه التلمیع فی الادب الفارسی', 'pageStart' => 107, 'pageEnd' => 120],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۱ هدف زندگی', 'pageStart' => 1, 'pageEnd' => 27],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۲ پر پرواز', 'pageStart' => 28, 'pageEnd' => 39],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۳ پنجره ای به روشنایی', 'pageStart' => 40, 'pageEnd' => 51],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۴ آینده روشن', 'pageStart' => 52, 'pageEnd' => 63],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۵ منزلگاه بعد', 'pageStart' => 64, 'pageEnd' => 73],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۶ واقعه بزرگ', 'pageStart' => 74, 'pageEnd' => 83],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۷ فرجام کار', 'pageStart' => 84, 'pageEnd' => 97],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۸ آهنگ سفر', 'pageStart' => 98, 'pageEnd' => 109],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۹ دوستی با خدا', 'pageStart' => 110, 'pageEnd' => 121],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۱۰ یاری از نماز و روزه', 'pageStart' => 122, 'pageEnd' => 135],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۱۱ فضیلت آراستگی', 'pageStart' => 136, 'pageEnd' => 145],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۱۲ زیبایی پوشیدگی', 'pageStart' => 146, 'pageEnd' => 152],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Conversation', 'pageStart' => 15, 'pageEnd' => 19],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'New Words', 'pageStart' => 20, 'pageEnd' => 21],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Reading', 'pageStart' => 22, 'pageEnd' => 23],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Grammer', 'pageStart' => 24, 'pageEnd' => 29],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Listening & Speaking', 'pageStart' => 30, 'pageEnd' => 33],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Writing', 'pageStart' => 34, 'pageEnd' => 41],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Conversation', 'pageStart' => 43, 'pageEnd' => 47],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'New Words', 'pageStart' => 48, 'pageEnd' => 49],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Reading', 'pageStart' => 50, 'pageEnd' => 51],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Grammer', 'pageStart' => 52, 'pageEnd' => 57],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Listening & Speaking', 'pageStart' => 58, 'pageEnd' => 61],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Writing', 'pageStart' => 62, 'pageEnd' => 69],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Conversation', 'pageStart' => 71, 'pageEnd' => 76],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'New Words', 'pageStart' => 77, 'pageEnd' => 79],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Reading', 'pageStart' => 80, 'pageEnd' => 81],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Grammer', 'pageStart' => 82, 'pageEnd' => 86],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Listening & Speaking', 'pageStart' => 87, 'pageEnd' => 90],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Writing', 'pageStart' => 91, 'pageEnd' => 95],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Conversation', 'pageStart' => 97, 'pageEnd' => 102],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'New Words', 'pageStart' => 103, 'pageEnd' => 104],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Reading', 'pageStart' => 105, 'pageEnd' => 106],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Grammer', 'pageStart' => 107, 'pageEnd' => 111],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Listening & Speaking', 'pageStart' => 112, 'pageEnd' => 114],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Writing', 'pageStart' => 115, 'pageEnd' => 119],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'عنصر ها چگونه پدید آمدند؟', 'pageStart' => 1, 'pageEnd' => 4],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'آیا همه ی اتم های یک عنصر پایدارند؟', 'pageStart' => 5, 'pageEnd' => 6],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تکنسیم، نخستین عنصر ساخت بشر', 'pageStart' => 7, 'pageEnd' => 9],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'طبقه بندی عنصر ها', 'pageStart' => 10, 'pageEnd' => 13],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'جرم اتمی عنصرها', 'pageStart' => 14, 'pageEnd' => 15],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'شمارش ذره ها از روی جرم آن ها', 'pageStart' => 16, 'pageEnd' => 18],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'نور کلید شناخت جهان', 'pageStart' => 19, 'pageEnd' => 21],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'نشر نور و طیف نشری', 'pageStart' => 22, 'pageEnd' => 23],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'ساختار اتم', 'pageStart' => 24, 'pageEnd' => 27],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'توزیع الکترون ها در لایه ها و زیر لایه ها', 'pageStart' => 28, 'pageEnd' => 29],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'آرایش الکترونی اتم', 'pageStart' => 30, 'pageEnd' => 34],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'ساختار اتم و رفتار آن', 'pageStart' => 35, 'pageEnd' => 37],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تبدیل اتم ها به یون ها', 'pageStart' => 38, 'pageEnd' => 39],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تبدیل اتم ها به مولکول ها', 'pageStart' => 40, 'pageEnd' => 41],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تمرین دوره ای', 'pageStart' => 42, 'pageEnd' => 46],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'هوا معجونی ارزشمند', 'pageStart' => 47, 'pageEnd' => 53],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اکسیژن گازی واکنش پذیر در هواکره', 'pageStart' => 54, 'pageEnd' => 55],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'ترکیب اکسیژن با فلز ها و نافلز ها', 'pageStart' => 56, 'pageEnd' => 57],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اکسیدها در فرآورده های سوختن', 'pageStart' => 58, 'pageEnd' => 59],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'رفتار اکسیدهای فلزی و نافلزی', 'pageStart' => 60, 'pageEnd' => 61],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'واکنش های شیمیایی و قانون پایستگی جرم', 'pageStart' => 62, 'pageEnd' => 63],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'موازنه کردن معادله واکنش های شیمیایی', 'pageStart' => 64, 'pageEnd' => 65],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'چه بر سر هواکره می آوریم', 'pageStart' => 66, 'pageEnd' => 67],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اثر گلخانه ای', 'pageStart' => 68, 'pageEnd' => 69],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'شیمی سبز', 'pageStart' => 70, 'pageEnd' => 72],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اوزون دگر شکلی از اکسیژن در هواکره', 'pageStart' => 73, 'pageEnd' => 75],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'رفتار گاز ها', 'pageStart' => 76, 'pageEnd' => 78],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'از هر گاز چقدر؟', 'pageStart' => 79, 'pageEnd' => 80],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'تولید آمونیاک', 'pageStart' => 81, 'pageEnd' => 82],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'تمرین دوره ای', 'pageStart' => 83, 'pageEnd' => 84],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'همراهان ناپیدای آب', 'pageStart' => 85, 'pageEnd' => 92],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'محلول و مقدار حل شونده', 'pageStart' => 93, 'pageEnd' => 94],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'قسمت در میلیون', 'pageStart' => 95, 'pageEnd' => 97],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'مولار', 'pageStart' => 98, 'pageEnd' => 99],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'آیا نمک ها به یک اندازه در آب حل می شوند؟', 'pageStart' => 100, 'pageEnd' => 103],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'رفتار آب و دیگر مولکول ها در میدان الکتریکی', 'pageStart' => 104, 'pageEnd' => 105],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'نیروهای بین مولکولی آب', 'pageStart' => 106, 'pageEnd' => 107],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'پیوند های هیدروژنی در حالت های فیزیکی گوناگون', 'pageStart' => 108, 'pageEnd' => 108],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'آب و دیگر حلال ها', 'pageStart' => 109, 'pageEnd' => 110],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'کدام مواد با یکدیگر محلول می سازند؟', 'pageStart' => 111, 'pageEnd' => 111],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'فرآیند انحلال نمک ها در آب', 'pageStart' => 112, 'pageEnd' => 112],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'آیا گاز ها هم در آب حل می شوند؟', 'pageStart' => 113, 'pageEnd' => 115],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'رد پای آب در زندگی', 'pageStart' => 116, 'pageEnd' => 119],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'تمرین دوره ای', 'pageStart' => 120, 'pageEnd' => 122],
            ['course_id' => 6, 'season' => 'فصل ۱ مجموعه، الگو و دنباله', 'content' => 'درس ۱ مجموعه های متناهی و نامتناهی', 'pageStart' => 1, 'pageEnd' => 7],
            ['course_id' => 6, 'season' => 'فصل ۱ مجموعه، الگو و دنباله', 'content' => 'درس ۲ متمم یک مجموعه', 'pageStart' => 8, 'pageEnd' => 13],
            ['course_id' => 6, 'season' => 'فصل ۱ مجموعه، الگو و دنباله', 'content' => 'درس ۳ الگو و دنباله', 'pageStart' => 14, 'pageEnd' => 20],
            ['course_id' => 6, 'season' => 'فصل ۱ مجموعه، الگو و دنباله', 'content' => 'درس ۴ دنباله های حسابی و هندسی', 'pageStart' => 21, 'pageEnd' => 27],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'درس ۱ نسبت های مثلثاتی', 'pageStart' => 28, 'pageEnd' => 35],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'درس ۲ دایره مثلثاتی', 'pageStart' => 36, 'pageEnd' => 41],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'درس ۳ روابط بین نسبت های مثلثاتی', 'pageStart' => 42, 'pageEnd' => 48],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'درس ۴ تعیین علامت نسبت های مثلثاتی', 'pageStart' => 49, 'pageEnd' => 53],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'درس ۵ تعیین نسبت های مثلثاتی یک زاویه', 'pageStart' => 54, 'pageEnd' => 60],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'درس ۶ جمع و تفاضل زاویه ها', 'pageStart' => 61, 'pageEnd' => 67],
            ['course_id' => 6, 'season' => 'فصل ۲ مثلثات', 'content' => 'تمرین دوره ای', 'pageStart' => 68, 'pageEnd' => 72],

            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => '۱ فیزیک دانش بنیادی', 'pageStart' => 1, 'pageEnd' => 4],
            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => '۲ مدل سازی در فیزیک', 'pageStart' => 5, 'pageEnd' => 5],
            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => '۳ اندازه گیری و کمیت های فیزیکی', 'pageStart' => 6, 'pageEnd' => 6],
            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => '۴ اندازه گیری و دستگاه بین المللی یکاها', 'pageStart' => 7, 'pageEnd' => 13],
            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => '۵ اندازی گیری و دقت وسیله های اندازی گیری', 'pageStart' => 14, 'pageEnd' => 15],
            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => '۶ چگالی', 'pageStart' => 16, 'pageEnd' => 18],
            ['course_id' => 7, 'season' => 'فصل ۱ فیزیک و اندازه گیری', 'content' => 'پرسش ها', 'pageStart' => 19, 'pageEnd' => 22],
            ['course_id' => 7, 'season' => 'فصل ۲ ویژگی های فیزیکی مواد', 'content' => '۱ حالت های ماده', 'pageStart' => 23, 'pageEnd' => 27],
            ['course_id' => 7, 'season' => 'فصل ۲ ویژگی های فیزیکی مواد', 'content' => '۲ نیروهای بین مولکولی', 'pageStart' => 28, 'pageEnd' => 31],
            ['course_id' => 7, 'season' => 'فصل ۲ ویژگی های فیزیکی مواد', 'content' => '۳ فشار در شاره ها', 'pageStart' => 32, 'pageEnd' => 39],
            ['course_id' => 7, 'season' => 'فصل ۲ ویژگی های فیزیکی مواد', 'content' => '۴ شناوری', 'pageStart' => 40, 'pageEnd' => 42],
            ['course_id' => 7, 'season' => 'فصل ۲ ویژگی های فیزیکی مواد', 'content' => '۵ شاره در حرکت و اصل برنولی', 'pageStart' => 43, 'pageEnd' => 47],
            ['course_id' => 7, 'season' => 'فصل ۲ ویژگی های فیزیکی مواد', 'content' => 'پرسش ها', 'pageStart' => 48, 'pageEnd' => 52],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۱ انرژی جنبشی', 'pageStart' => 53, 'pageEnd' => 54],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۲ کار انجام شده توسط نیروی ثابت', 'pageStart' => 55, 'pageEnd' => 60],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۳ کار و انرژی جنبشی', 'pageStart' => 61, 'pageEnd' => 63],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۴ کار و انرژی پتانسیل', 'pageStart' => 64, 'pageEnd' => 67],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۵ پایستگی انرژی مکانیکی', 'pageStart' => 68, 'pageEnd' => 70],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۶ کار و انرژی درونی', 'pageStart' => 71, 'pageEnd' => 72],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => '۷ توان', 'pageStart' => 73, 'pageEnd' => 77],
            ['course_id' => 7, 'season' => 'فصل ۳ کار، انرژی و توان', 'content' => 'پرسش ها', 'pageStart' => 78, 'pageEnd' => 82],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => '۱ دما و دماسنجی', 'pageStart' => 83, 'pageEnd' => 86],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => '۲ انبساط گرمایی', 'pageStart' => 87, 'pageEnd' => 95],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => '۳ گرما', 'pageStart' => 96, 'pageEnd' => 102],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => '۴ تغییر حالت های ماده', 'pageStart' => 103, 'pageEnd' => 110],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => '۵ روش های انتقال گرما', 'pageStart' => 111, 'pageEnd' => 116],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => '۶ قوانین گازها', 'pageStart' => 117, 'pageEnd' => 123],
            ['course_id' => 7, 'season' => 'فصل ۴ دما و گرما', 'content' => 'پرسش ها', 'pageStart' => 124, 'pageEnd' => 126],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۱ معادله ی حالت و فرآیندهای ترمودینامیکی ایستاور', 'pageStart' => 127, 'pageEnd' => 128],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۲ تبادل انرژی', 'pageStart' => 129, 'pageEnd' => 129],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۳ انرژی درونی و قانون اول ترمودینامیک', 'pageStart' => 130, 'pageEnd' => 130],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۴ برخی از فرآیند های ترمودینامیکی', 'pageStart' => 131, 'pageEnd' => 138],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۵ چرخه ترمودینامیکی', 'pageStart' => 139, 'pageEnd' => 139],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۶ ماشین گرمایی', 'pageStart' => 140, 'pageEnd' => 145],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۷ قانون دوم ترمودینامیک به بیان ماشین گرمایی', 'pageStart' => 146, 'pageEnd' => 146],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => '۸ قانون دوم ترمودینامیک و یخچال', 'pageStart' => 147, 'pageEnd' => 147],
            ['course_id' => 7, 'season' => 'فصل ۵ ترمودینامیک', 'content' => 'پرسش ها', 'pageStart' => 148, 'pageEnd' => 149],


            ['course_id' => 9, 'season' => 'فصل ۱ دنیای زنده', 'content' => 'گفتار ۱ زیست شناسی چیست', 'pageStart' => 1, 'pageEnd' => 6],
            ['course_id' => 9, 'season' => 'فصل ۱ دنیای زنده', 'content' => 'گفتار ۲ گستره حیات', 'pageStart' => 7, 'pageEnd' => 10],
            ['course_id' => 9, 'season' => 'فصل ۱ دنیای زنده', 'content' => 'گفتار ۳ یاخته و بافت در بدن انسان', 'pageStart' => 11, 'pageEnd' => 16],
            ['course_id' => 9, 'season' => 'فصل ۲ گوارش و جذب مواد', 'content' => 'گفتار ۱ ساختار و عملکرد لوله گوارش', 'pageStart' => 17, 'pageEnd' => 24],
            ['course_id' => 9, 'season' => 'فصل ۲ گوارش و جذب مواد', 'content' => 'گفتار ۲ جذب مواد و تنظیم فعالیت دستگاه گوارش', 'pageStart' => 25, 'pageEnd' => 29],
            ['course_id' => 9, 'season' => 'فصل ۲ گوارش و جذب مواد', 'content' => 'گفتار ۳ تنوع گوارش در جانداران', 'pageStart' => 30, 'pageEnd' => 32],
            ['course_id' => 9, 'season' => 'فصل ۳ تبادلات گازی', 'content' => 'گفتار ۱ ساز و کار دستگاه تنفس در انسان', 'pageStart' => 33, 'pageEnd' => 39],
            ['course_id' => 9, 'season' => 'فصل ۳ تبادلات گازی', 'content' => 'گفتار ۲ تهویه ششی', 'pageStart' => 40, 'pageEnd' => 44],
            ['course_id' => 9, 'season' => 'فصل ۳ تبادلات گازی', 'content' => 'گفتار ۳ تنوع تبادلات گازی', 'pageStart' => 45, 'pageEnd' => 46],
            ['course_id' => 9, 'season' => 'فصل ۴ گردش مواد در بدن', 'content' => 'گفتار ۱ قلب', 'pageStart' => 47, 'pageEnd' => 54],
            ['course_id' => 9, 'season' => 'فصل ۴ گردش مواد در بدن', 'content' => 'گفتار ۲ رگ ها', 'pageStart' => 55, 'pageEnd' => 60],
            ['course_id' => 9, 'season' => 'فصل ۴ گردش مواد در بدن', 'content' => 'گفتار ۳ خون', 'pageStart' => 61, 'pageEnd' => 64],
            ['course_id' => 9, 'season' => 'فصل ۴ گردش مواد در بدن', 'content' => 'گفتار ۴ تنوع گردش مواد در جانداران', 'pageStart' => 65, 'pageEnd' => 68],
            ['course_id' => 9, 'season' => 'فصل ۵ تنظیم اسمزی و دفع مواد زائد', 'content' => 'گفتار ۱ هم ایستایی و کلیه ها', 'pageStart' => 69, 'pageEnd' => 72],


                ['course_id' => 9, 'season' => 'فصل ۵ تنظیم اسمزی و دفع مواد زائد', 'content' => 'گفتار ۲ تشکیل ادرار و تخلیه آن', 'pageStart' => 73, 'pageEnd' => 75],
                ['course_id' => 9, 'season' => 'فصل ۵ تنظیم اسمزی و دفع مواد زائد', 'content' => 'گفتار ۳ تنوع دفع و تنظیم اسمزی در جانداران', 'pageStart' => 76, 'pageEnd' => 78],
                ['course_id' => 9, 'season' => 'فصل ۶ از یاخته تا گیاه', 'content' => 'گفتار ۱ ویژگی های یاخته گیاهی', 'pageStart' => 79, 'pageEnd' => 85],
                ['course_id' => 9, 'season' => 'فصل ۶ از یاخته تا گیاه', 'content' => 'گفتار ۲ سامانه بافتی', 'pageStart' => 86, 'pageEnd' => 89],
                ['course_id' => 9, 'season' => 'فصل ۶ از یاخته تا گیاه', 'content' => 'گفتار ۳ ساختار گیاهان', 'pageStart' => 90, 'pageEnd' => 96],
                ['course_id' => 9, 'season' => 'فصل ۷ جذب و انتقال مواد در گیاهان', 'content' => 'گفتار ۱ تغذیه گیاهی', 'pageStart' => 97, 'pageEnd' => 101],
                ['course_id' => 9, 'season' => 'فصل ۷ جذب و انتقال مواد در گیاهان', 'content' => 'گفتار ۲ جانداران موثر در تغذیه گیاهان', 'pageStart' => 102, 'pageEnd' => 104],
                ['course_id' => 9, 'season' => 'فصل ۷ جذب و انتقال مواد در گیاهان', 'content' => 'گفتار ۳ انتقال مواد در گیاهان', 'pageStart' => 105, 'pageEnd' => 111],
                ['course_id' => 16, 'season' => 'فصل ۱ ترسیم های هندسی و استدلال', 'content' => 'درس ۱ ترسیم های هندسی', 'pageStart' => 9, 'pageEnd' => 16],
                ['course_id' => 16, 'season' => 'فصل ۱ ترسیم های هندسی و استدلال', 'content' => 'درس ۲ استدلال', 'pageStart' => 17, 'pageEnd' => 28],
                ['course_id' => 16, 'season' => 'فصل ۲ قضیه تالس، تشابه و کاربردهای آن', 'content' => 'درس ۱ نسبت و تناسب در هندسه', 'pageStart' => 29, 'pageEnd' => 33],
                ['course_id' => 16, 'season' => 'فصل ۲ قضیه تالس، تشابه و کاربردهای آن', 'content' => 'درس ۲ قضیه تالس', 'pageStart' => 34, 'pageEnd' => 37],
                ['course_id' => 16, 'season' => 'فصل ۲ قضیه تالس، تشابه و کاربردهای آن', 'content' => 'درس ۳ تشابه مثلث ها', 'pageStart' => 38, 'pageEnd' => 44],
                ['course_id' => 16, 'season' => 'فصل ۲ قضیه تالس، تشابه و کاربردهای آن', 'content' => 'درس ۴ کاربردهایی از قضیه تالس و تشابه مثلث ها', 'pageStart' => 45, 'pageEnd' => 52],
                ['course_id' => 16, 'season' => 'فصل ۳ چند ضلعی ها', 'content' => 'درس ۱ چند ضلعی ها و ویژگی هایی از آنها', 'pageStart' => 53, 'pageEnd' => 64],
                ['course_id' => 16, 'season' => 'فصل ۳ چند ضلعی ها', 'content' => 'درس ۲ مساحت و کاربردهای آن', 'pageStart' => 65, 'pageEnd' => 76],
                ['course_id' => 16, 'season' => 'فصل ۴ تجسم فضایی', 'content' => 'درس ۱ خط ، نقطه و صفحه', 'pageStart' => 77, 'pageEnd' => 86],
                ['course_id' => 16, 'season' => 'فصل ۴ تجسم فضایی', 'content' => 'درس ۲ تفکر تجسمی', 'pageStart' => 87, 'pageEnd' => 96],
                ['course_id' => 11, 'season' => 'فصل ۱ جغرافیا چیست', 'content' => 'درس ۱ جغرافیا، علمی برای زندگی بهتر', 'pageStart' => 2, 'pageEnd' => 7],
                ['course_id' => 11, 'season' => 'فصل ۱ جغرافیا چیست', 'content' => 'درس ۲ روش مطالعه و پژوهش در جغرافیا', 'pageStart' => 8, 'pageEnd' => 13],
                ['course_id' => 11, 'season' => 'فصل ۲ جغرافیای طبیعی ایران', 'content' => 'درس ۳ موقعیت جغرافیایی ایران', 'pageStart' => 14, 'pageEnd' => 21],
                ['course_id' => 11, 'season' => 'فصل ۲ جغرافیای طبیعی ایران', 'content' => 'درس ۴ ناهمواری های ایران', 'pageStart' => 22, 'pageEnd' => 33],
                ['course_id' => 11, 'season' => 'فصل ۲ جغرافیای طبیعی ایران', 'content' => 'درس ۵ آب و هوای ایران', 'pageStart' => 34, 'pageEnd' => 46],
                ['course_id' => 11, 'season' => 'فصل ۲ جغرافیای طبیعی ایران', 'content' => 'درس ۶ منابع آب ایران', 'pageStart' => 47, 'pageEnd' => 63],
                ['course_id' => 11, 'season' => 'فصل ۳ جغرافیای انسانی ایران', 'content' => 'درس ۷ ویژگی های جمعیت ایران', 'pageStart' => 64, 'pageEnd' => 76],
                ['course_id' => 11, 'season' => 'فصل ۳ جغرافیای انسانی ایران', 'content' => 'درس ۸ تقسیمات کشوری ایران', 'pageStart' => 77, 'pageEnd' => 82],
                ['course_id' => 11, 'season' => 'فصل ۳ جغرافیای انسانی ایران', 'content' => 'درس ۹ سکونتگاه های ایران', 'pageStart' => 83, 'pageEnd' => 93],
                ['course_id' => 11, 'season' => 'فصل ۳ جغرافیای انسانی ایران', 'content' => 'درس ۱۰ توان های اقتصادی ایران', 'pageStart' => 94, 'pageEnd' => 106],
                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس اول: هدف زندگی', 'pageStart' => 11, 'pageEnd' => 27],

                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس دوم: پر پرواز', 'pageStart' => 28, 'pageEnd' => 39],
                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس سوم: پنجره‌ای به روشنایی', 'pageStart' => 40, 'pageEnd' => 51],
                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس چهارم: آیند روشن', 'pageStart' => 52, 'pageEnd' => 63],
                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس پنجم: منزلگاه بعد', 'pageStart' => 64, 'pageEnd' => 73],
                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس ششم: واقعه بزرگ', 'pageStart' => 74, 'pageEnd' => 83],
                ['course_id' => 3, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس هفتم: فرجام کار', 'pageStart' => 84, 'pageEnd' => 97],
                ['course_id' => 3, 'season' => 'بخش دوم: قدم در راه', 'content' => 'درس هشتم: آهنگ سفر', 'pageStart' => 98, 'pageEnd' => 109],
                ['course_id' => 3, 'season' => 'بخش دوم: قدم در راه', 'content' => 'درس نهم: دوستی با خدا', 'pageStart' => 110, 'pageEnd' => 121],
                ['course_id' => 3, 'season' => 'بخش دوم: قدم در راه', 'content' => 'درس دهم: یازی از نماز و روزه', 'pageStart' => 122, 'pageEnd' => 135],
                ['course_id' => 3, 'season' => 'بخش دوم: قدم در راه', 'content' => 'درس یازدهم: فضیلت آراستگی', 'pageStart' => 136, 'pageEnd' => 145],
                ['course_id' => 3, 'season' => 'بخش دوم: قدم در راه', 'content' => 'درس دوازدهم: زیبایی پوشیدگی', 'pageStart' => 146, 'pageEnd' => 152],

                ['course_id' => 21, 'season' => 'الدرس الاول', 'content' => 'الدرس الاول', 'pageStart' => 1, 'pageEnd' => 18],
                ['course_id' => 21, 'season' => 'الدرس الثانی', 'content' => 'الدرس الثانی', 'pageStart' => 19, 'pageEnd' => 32],
                ['course_id' => 21, 'season' => 'الدرس الثالث', 'content' => 'الدرس الثالث', 'pageStart' => 33, 'pageEnd' => 48],
                ['course_id' => 21, 'season' => 'الدرس الرابع', 'content' => 'الدرس الرابع', 'pageStart' => 49, 'pageEnd' => 62],
                ['course_id' => 21, 'season' => 'الدرس الخامس', 'content' => 'الدرس الخامس', 'pageStart' => 63, 'pageEnd' => 74],
                ['course_id' => 21, 'season' => 'الدرس السادس', 'content' => 'الدرس السادس', 'pageStart' => 75, 'pageEnd' => 88],
                ['course_id' => 21, 'season' => 'الدرس السابع', 'content' => 'الدرس السابع', 'pageStart' => 89, 'pageEnd' => 101],

                ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'شروع', 'pageStart' => 1, 'pageEnd' => 5],
                ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'الگوها و روندها در رفتار عناصر', 'pageStart' => 6, 'pageEnd' => 10],
                ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'رفتار عنصرها و شعاع اتم', 'pageStart' => 11, 'pageEnd' => 14],
                ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'دنیایی رنگی با عنصرهای دسته d', 'pageStart' => 15, 'pageEnd' => 17],


            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'عنصرها به چه شکلی در طبیعت یافت می شوند؟', 'pageStart' => 18, 'pageEnd' => 21],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'دنیای واقعی واکنش ها', 'pageStart' => 22, 'pageEnd' => 25],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'گنج های اعماق دریا', 'pageStart' => 26, 'pageEnd' => 26],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'جریان فلز بین محیط زیست و جامعه d', 'pageStart' => 26, 'pageEnd' => 29],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'نفت، هدیه‌ای شگفت انگیز', 'pageStart' => 30, 'pageEnd' => 30],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'کربن، اساس استخوان بندی هیدرو کربن ها', 'pageStart' => 31, 'pageEnd' => 33],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'آلکان ها، هیدروکربن هایی با پیوند یگانه', 'pageStart' => 34, 'pageEnd' => 37],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'نام گذاری آلکان ها', 'pageStart' => 38, 'pageEnd' => 39],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'آلکن ها، هیدرو کربن هایی با یک پیوند دوگانه', 'pageStart' => 40, 'pageEnd' => 41],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'آلکین‌ها، سیرنشده تر از آلکن‌ها', 'pageStart' => 42, 'pageEnd' => 42],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'هیدروکربن‌‌های حلقوی', 'pageStart' => 43, 'pageEnd' => 43],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'نفت، ماده‌ای که اقتصاد جهان را دگرگون ساخت', 'pageStart' => 44, 'pageEnd' => 47],
            ['course_id' => 22, 'season' => 'فصل۱ قدر هدایای زمینی را بدانیم', 'content' => 'تمرین دوره‌ای', 'pageStart' => 48, 'pageEnd' => 50],

            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'شروع', 'pageStart' => 51, 'pageEnd' => 53],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'غذا، ماده و انرژی', 'pageStart' => 54, 'pageEnd' => 55],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'دمای یک ماده از چه خبر می‌دهد؟', 'pageStart' => 56, 'pageEnd' => 57],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'تهیه غذای آب‌پز، تجربه تفاوت دما و گرما', 'pageStart' => 58, 'pageEnd' => 60],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'جاری شدن انرژی گرمایی', 'pageStart' => 61, 'pageEnd' => 61],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'گرما در واکنش های شیمیایی (گرماشیمی)', 'pageStart' => 62, 'pageEnd' => 65],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'آنتالپی، همان محتوای انرژی است', 'pageStart' => 66, 'pageEnd' => 66],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'آنتالپی پیوند و میانگین آن', 'pageStart' => 67, 'pageEnd' => 68],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'آنتالپی پیوند، راهی برای تعیین دلتا اچ واکنش', 'pageStart' => 69, 'pageEnd' => 71],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'آنتالپی سوخت، تکیه گاهی برای تامین انرژی', 'pageStart' => 72, 'pageEnd' => 73],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'جمع‌پذیری گرمای واکنش‌ها، قانون هس', 'pageStart' => 74, 'pageEnd' => 77],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'غذای سالم', 'pageStart' => 78, 'pageEnd' => 78],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'آهنگ واکنش', 'pageStart' => 79, 'pageEnd' => 84],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'سرعت تولید یا مصرف مواد شرکت کننده در واکنش از دیدگاه کمی', 'pageStart' => 85, 'pageEnd' => 88],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'سرعت متوسط و شیب نمودار مول-زمان', 'pageStart' => 89, 'pageEnd' => 90],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'خوراکی های طبیعی رنگین، بازدارنده‌هایی مفید و موثر', 'pageStart' => 91, 'pageEnd' => 91],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'سرعت واکنش', 'pageStart' => 92, 'pageEnd' => 93],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'غذا، پسماند و ردپای آن', 'pageStart' => 94, 'pageEnd' => 95],
            ['course_id' => 22, 'season' => 'فصل۲ در پی غذای سالم', 'content' => 'تمرین دوره‌ای', 'pageStart' => 96, 'pageEnd' => 98],

            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'شروع', 'pageStart' => 99, 'pageEnd' => 101],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'الیاف و درشت مولکول‌ها', 'pageStart' => 102, 'pageEnd' => 103],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'پلیمری شدن (بسپارش)', 'pageStart' => 104, 'pageEnd' => 109],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'پلی استرها', 'pageStart' => 110, 'pageEnd' => 110],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'الکل‌ها و اسیدها', 'pageStart' => 111, 'pageEnd' => 113],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'واکنش استری شدن', 'pageStart' => 114, 'pageEnd' => 115],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'پلی آمیدها', 'pageStart' => 116, 'pageEnd' => 117],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'پلیمرها، ماندگار یا تخریب‌پذیر', 'pageStart' => 118, 'pageEnd' => 120],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'پلیمر سبز', 'pageStart' => 121, 'pageEnd' => 121],
            ['course_id' => 22, 'season' => 'فصل۳ پوشاک، نیازی پایان‌ناپذیر', 'content' => 'تمرین دوره‌ای', 'pageStart' => 122, 'pageEnd' => 123],


            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'شروع', 'pageStart' => 9, 'pageEnd' => 11],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس اول: هدایت الهی', 'pageStart' => 12, 'pageEnd' => 21],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس دوم: تداوم هدایت', 'pageStart' => 22, 'pageEnd' => 35],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس سوم: معجزه جاویدان', 'pageStart' => 36, 'pageEnd' => 47],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس چهارم: مسئولیت های پیامبر', 'pageStart' => 48, 'pageEnd' => 61],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس پنجم: امامت، تداوم رسالت', 'pageStart' => 62, 'pageEnd' => 73],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس ششم: پیشوایان اسوه', 'pageStart' => 74, 'pageEnd' => 87],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس هفتم: وضعیت فرهنگی، اجتماعی و سیاسی مسلمانان، پس از رحلت رسول خدا', 'pageStart' => 88, 'pageEnd' => 97],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس هشتم: احیای ارزش هاس راستین', 'pageStart' => 98, 'pageEnd' => 109],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس نهم: عصر غیبت', 'pageStart' => 110, 'pageEnd' => 123],
            ['course_id' => 20, 'season' => 'بخش اول: تفکر و اندیشه', 'content' => 'درس دهم: مرجعیت و ولایت فقیه', 'pageStart' => 124, 'pageEnd' => 133],
            ['course_id' => 20, 'season' => 'بخش دوم: در مسیر', 'content' => 'شروع', 'pageStart' => 134, 'pageEnd' => 137],
            ['course_id' => 20, 'season' => 'بخش دوم: در مسیر', 'content' => 'درس یازدهم: عزت نفس', 'pageStart' => 138, 'pageEnd' => 147],
            ['course_id' => 20, 'season' => 'بخش دوم: در مسیر', 'content' => 'درس دوازدهم: پیوند مقدس', 'pageStart' => 148, 'pageEnd' => 158],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'بار الکتریکی', 'pageStart' => 1, 'pageEnd' => 2],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'دایستگی و کوانتیده بودن بار الکتریکی', 'pageStart' => 3, 'pageEnd' => 4],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'قانون کولن', 'pageStart' => 5, 'pageEnd' => 9],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'میدان الکتریکی', 'pageStart' => 10, 'pageEnd' => 11],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'میدان الکتریکی حاصل از یک ذره باردار', 'pageStart' => 12, 'pageEnd' => 16],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'خطوط میدان الکتریکی', 'pageStart' => 17, 'pageEnd' => 20],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'انرژی پتانسیل الکتریکی', 'pageStart' => 21, 'pageEnd' => 22],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'پتانسیل الکتریکی', 'pageStart' => 23, 'pageEnd' => 26],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'میدان الکتریکی در داخل رساناها', 'pageStart' => 27, 'pageEnd' => 31],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'خازن', 'pageStart' => 32, 'pageEnd' => 33],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'خازن با دی الکتریک', 'pageStart' => 34, 'pageEnd' => 37],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'انرژی خازن', 'pageStart' => 38, 'pageEnd' => 40],
            ['course_id' => 27, 'season' => 'الکتریسیته ساکن', 'content' => 'پرسش‌ها', 'pageStart' => 41, 'pageEnd' => 44],

            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'جریان الکتریکی', 'pageStart' => 45, 'pageEnd' => 48],
            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'مقاومت الکتریکی و قانون اهم', 'pageStart' => 49, 'pageEnd' => 50],
            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'عوامل موثر بر مقاومت الکتریکی', 'pageStart' => 51, 'pageEnd' => 60],
            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'نیروی محرکه الکتریکی و مدارها', 'pageStart' => 61, 'pageEnd' => 66],
            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'توان در مدارهای الکتریکی', 'pageStart' => 67, 'pageEnd' => 69],
            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'ترکیب مقاومت‌ها', 'pageStart' => 70, 'pageEnd' => 78],
            ['course_id' => 27, 'season' => 'جریان الکتریکی و مدارهای جریان مستقیم', 'content' => 'پرسش‌ها', 'pageStart' => 79, 'pageEnd' => 82],

            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'مغناطیس و قطب های مغناطیسی', 'pageStart' => 83, 'pageEnd' => 84],
            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'میدان مغناطیسی', 'pageStart' => 85, 'pageEnd' => 88],
            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'نیروی مغناطیسی وارد بر ذره باردار متحرک در میدان مغناطیسی', 'pageStart' => 89, 'pageEnd' => 90],
            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'نیروی مغناطیسی وارد بر سیم حامل جریان', 'pageStart' => 91, 'pageEnd' => 93],
            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'میدان مغناطیسی حاصل از جریان الکتریکی', 'pageStart' => 94, 'pageEnd' => 100],
            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'ویژگی های مغناطیسی مواد', 'pageStart' => 101, 'pageEnd' => 103],
            ['course_id' => 27, 'season' => 'مغناطیس', 'content' => 'پرسش ها', 'pageStart' => 104, 'pageEnd' => 108],

            ['course_id' => 27, 'season' => 'القای الکترومغناطیسی و جریان متناوب', 'content' => 'پدیده القای الکترومغناطیسی', 'pageStart' => 109, 'pageEnd' => 110],
            ['course_id' => 27, 'season' => 'القای الکترومغناطیسی و جریان متناوب', 'content' => 'قانون القای الکترومغناطیسی فاراده', 'pageStart' => 111, 'pageEnd' => 116],
            ['course_id' => 27, 'season' => 'القای الکترومغناطیسی و جریان متناوب', 'content' => 'قانون لنز', 'pageStart' => 117, 'pageEnd' => 117],
            ['course_id' => 27, 'season' => 'القای الکترومغناطیسی و جریان متناوب', 'content' => 'القاگرها', 'pageStart' => 118, 'pageEnd' => 121],
            ['course_id' => 27, 'season' => 'القای الکترومغناطیسی و جریان متناوب', 'content' => 'جریان متناوب', 'pageStart' => 122, 'pageEnd' => 127],
            ['course_id' => 27, 'season' => 'القای الکترومغناطیسی و جریان متناوب', 'content' => 'پرسش‌ها', 'pageStart' => 128, 'pageEnd' => 130],



        ]);
    }
}
