<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ContentSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        DB::table('contents')->delete();

        DB::table('contents')->insert([
            ['course_id' => 1, 'season' => 'ادبیات تعلیمی', 'content' => 'درس ۱', 'pageStart' => 1, 'pageEnd' => 17],
            ['course_id' => 1, 'season' => 'ادبیات تعلیمی', 'content' => 'درس ۲', 'pageStart' => 18, 'pageEnd' => 30],
            ['course_id' => 1, 'season' => 'ادبیات پایداری', 'content' => 'درس ۳', 'pageStart' => 31, 'pageEnd' => 36],
            ['course_id' => 1, 'season' => 'ادبیات پایداری', 'content' => 'درس ۴', 'pageStart' => 37, 'pageEnd' => 38],
            ['course_id' => 1, 'season' => 'ادبیات پایداری', 'content' => 'درس ۵', 'pageStart' => 39, 'pageEnd' => 46],
            ['course_id' => 1, 'season' => 'ادبیات غنایی', 'content' => 'درس ۶', 'pageStart' => 47, 'pageEnd' => 50],
            ['course_id' => 1, 'season' => 'ادبیات غنایی', 'content' => 'درس ۷', 'pageStart' => 51, 'pageEnd' => 58],
            ['course_id' => 1, 'season' => 'ادبیات سفر و زندگی', 'content' => 'درس ۸', 'pageStart' => 59, 'pageEnd' => 63],
            ['course_id' => 1, 'season' => 'ادبیات سفر و زندگی', 'content' => 'درس ۹', 'pageStart' => 64, 'pageEnd' => 74],
            ['course_id' => 1, 'season' => 'ادبیات انقلاب اسلامی', 'content' => 'درس ۱۰', 'pageStart' => 75, 'pageEnd' => 81],
            ['course_id' => 1, 'season' => 'ادبیات انقلاب اسلامی', 'content' => 'درس ۱۱', 'pageStart' => 82, 'pageEnd' => 94],
            ['course_id' => 1, 'season' => 'ادبیات حماسی', 'content' => 'درس ۱۲', 'pageStart' => 95, 'pageEnd' => 101],
            ['course_id' => 1, 'season' => 'ادبیات حماسی', 'content' => 'درس ۱۳', 'pageStart' => 102, 'pageEnd' => 112],
            ['course_id' => 1, 'season' => 'ادبیات داستانی', 'content' => 'درس ۱۴', 'pageStart' => 113, 'pageEnd' => 117],
            ['course_id' => 1, 'season' => 'ادبیات داستانی', 'content' => 'درس ۱۵', 'pageStart' => 118, 'pageEnd' => 119],
            ['course_id' => 1, 'season' => 'ادبیات داستانی', 'content' => 'درس ۱۶', 'pageStart' => 120, 'pageEnd' => 132],
            ['course_id' => 1, 'season' => 'ادبیات جهان', 'content' => 'درس ۱۷', 'pageStart' => 133, 'pageEnd' => 139],
            ['course_id' => 1, 'season' => 'ادبیات جهان', 'content' => 'درس ۱۸', 'pageStart' => 140, 'pageEnd' => 149],
            ['course_id' => 4, 'season' => 'الدرس الاول', 'content' => 'ذلک هو الله', 'pageStart' => 1, 'pageEnd' => 14],
            ['course_id' => 4, 'season' => 'الدرس الثانی', 'content' => 'المواعظ العددیه', 'pageStart' => 15, 'pageEnd' => 28],
            ['course_id' => 4, 'season' => 'الدرس الثالث', 'content' => 'مطر السمک', 'pageStart' => 29, 'pageEnd' => 46],
            ['course_id' => 4, 'season' => 'الدرس الرابع', 'content' => 'التعایش السلمی', 'pageStart' => 47, 'pageEnd' => 62],
            ['course_id' => 4, 'season' => 'الدرس الخامس', 'content' => 'هذا خلق الله', 'pageStart' => 63, 'pageEnd' => 78],
            ['course_id' => 4, 'season' => 'الدرس السادس', 'content' => 'ذوالقرنین', 'pageStart' => 79, 'pageEnd' => 90],
            ['course_id' => 4, 'season' => 'الدرس السابع', 'content' => 'یا من فی البحار عجائبه', 'pageStart' => 91, 'pageEnd' => 106],
            ['course_id' => 4, 'season' => 'الدرس الثامن', 'content' => 'صناعه التلمیع فی الادب الفارسی', 'pageStart' => 107, 'pageEnd' => 120],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۱ هدف زندگی', 'pageStart' => 1, 'pageEnd' => 27],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۲ پر پرواز', 'pageStart' => 28, 'pageEnd' => 39],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۳ پنجره ای به روشنایی', 'pageStart' => 40, 'pageEnd' => 51],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۴ آینده روشن', 'pageStart' => 52, 'pageEnd' => 63],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۵ منزلگاه بعد', 'pageStart' => 64, 'pageEnd' => 73],
            ['course_id' => 3, 'season' => 'تفکر و اندیشه', 'content' => 'درس ۶ واقعه بزرگ', 'pageStart' => 74, 'pageEnd' => 83],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۷ فرجام کار', 'pageStart' => 84, 'pageEnd' => 97],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۸ آهنگ سفر', 'pageStart' => 98, 'pageEnd' => 109],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۹ دوستی با خدا', 'pageStart' => 110, 'pageEnd' => 121],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۱۰ یاری از نماز و روزه', 'pageStart' => 122, 'pageEnd' => 135],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۱۱ فضیلت آراستگی', 'pageStart' => 136, 'pageEnd' => 145],
            ['course_id' => 3, 'season' => 'قدم در راه', 'content' => 'درس ۱۲ زیبایی پوشیدگی', 'pageStart' => 146, 'pageEnd' => 152],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Conversation', 'pageStart' => 15, 'pageEnd' => 19],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'New Words', 'pageStart' => 20, 'pageEnd' => 21],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Reading', 'pageStart' => 22, 'pageEnd' => 23],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Grammar', 'pageStart' => 24, 'pageEnd' => 29],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Listening & Speaking', 'pageStart' => 30, 'pageEnd' => 33],
            ['course_id' => 15, 'season' => 'Lesson 1', 'content' => 'Writing', 'pageStart' => 34, 'pageEnd' => 41],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Conversation', 'pageStart' => 43, 'pageEnd' => 47],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'New Words', 'pageStart' => 48, 'pageEnd' => 49],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Reading', 'pageStart' => 50, 'pageEnd' => 51],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Grammar', 'pageStart' => 52, 'pageEnd' => 57],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Listening & Speaking', 'pageStart' => 58, 'pageEnd' => 61],
            ['course_id' => 15, 'season' => 'Lesson 2', 'content' => 'Writing', 'pageStart' => 62, 'pageEnd' => 69],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Conversation', 'pageStart' => 71, 'pageEnd' => 76],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'New Words', 'pageStart' => 77, 'pageEnd' => 79],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Reading', 'pageStart' => 80, 'pageEnd' => 81],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Grammar', 'pageStart' => 82, 'pageEnd' => 86],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Listening & Speaking', 'pageStart' => 87, 'pageEnd' => 90],
            ['course_id' => 15, 'season' => 'Lesson 3', 'content' => 'Writing', 'pageStart' => 91, 'pageEnd' => 95],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Conversation', 'pageStart' => 97, 'pageEnd' => 102],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'New Words', 'pageStart' => 103, 'pageEnd' => 104],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Reading', 'pageStart' => 105, 'pageEnd' => 106],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Grammar', 'pageStart' => 107, 'pageEnd' => 111],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Listening & Speaking', 'pageStart' => 112, 'pageEnd' => 114],
            ['course_id' => 15, 'season' => 'Lesson 4', 'content' => 'Writing', 'pageStart' => 115, 'pageEnd' => 119],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'عنصر ها چگونه پدید آمدند؟', 'pageStart' => 1, 'pageEnd' => 4],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'آیا همه ی اتم های یک عنصر پایدارند؟', 'pageStart' => 5, 'pageEnd' => 6],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تکنسیم، نخستین عنصر ساخت بشر', 'pageStart' => 7, 'pageEnd' => 9],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'طبقه بندی عنصر ها', 'pageStart' => 10, 'pageEnd' => 13],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'جرم اتمی عنصرها', 'pageStart' => 14, 'pageEnd' => 15],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'شمارش ذره ها از روی جرم آن ها', 'pageStart' => 16, 'pageEnd' => 18],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'نور کلید شناخت جهان', 'pageStart' => 19, 'pageEnd' => 21],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'نشر نور و طیف نشری', 'pageStart' => 22, 'pageEnd' => 23],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'ساختار اتم', 'pageStart' => 24, 'pageEnd' => 27],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'توزیع الکترون ها در لایه ها و زیر لایه ها', 'pageStart' => 28, 'pageEnd' => 29],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'آرایش الکترونی اتم', 'pageStart' => 30, 'pageEnd' => 34],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'ساختار اتم و رفتار آن', 'pageStart' => 35, 'pageEnd' => 37],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تبدیل اتم ها به یون ها', 'pageStart' => 38, 'pageEnd' => 39],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تبدیل اتم ها به مولکول ها', 'pageStart' => 40, 'pageEnd' => 41],
            ['course_id' => 5, 'season' => 'فصل ۱ کیهان زادگاه الفبای هستی', 'content' => 'تمرین دوره ای', 'pageStart' => 42, 'pageEnd' => 46],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'هوا معجونی ارزشمند', 'pageStart' => 47, 'pageEnd' => 53],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اکسیژن گازی واکنش پذیر در هواکره', 'pageStart' => 54, 'pageEnd' => 55],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'ترکیب اکسیژن با فلز ها و نافلز ها', 'pageStart' => 56, 'pageEnd' => 57],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اکسیدها در فرآورده های سوختن', 'pageStart' => 58, 'pageEnd' => 59],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'رفتار اکسیدهای فلزی و نافلزی', 'pageStart' => 60, 'pageEnd' => 61],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'واکنش های شیمیایی و قانون پایستگی جرم', 'pageStart' => 62, 'pageEnd' => 63],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'موازنه کردن معادله واکنش های شیمیایی', 'pageStart' => 64, 'pageEnd' => 65],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'چه بر سر هواکره می آوریم', 'pageStart' => 66, 'pageEnd' => 67],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اثر گلخانه ای', 'pageStart' => 68, 'pageEnd' => 69],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'شیمی سبز', 'pageStart' => 70, 'pageEnd' => 72],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'اوزون دگر شکلی از اکسیژن در هواکره', 'pageStart' => 73, 'pageEnd' => 75],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'رفتار گاز ها', 'pageStart' => 76, 'pageEnd' => 78],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'از هر گاز چقدر؟', 'pageStart' => 79, 'pageEnd' => 80],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'تولید آمونیاک', 'pageStart' => 81, 'pageEnd' => 82],
            ['course_id' => 5, 'season' => 'فصل ۲ رد پای گاز ها', 'content' => 'تمرین دوره ای', 'pageStart' => 83, 'pageEnd' => 84],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'همراهان ناپیدای آب', 'pageStart' => 85, 'pageEnd' => 92],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'محلول و مقدار حل شونده', 'pageStart' => 93, 'pageEnd' => 94],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'قسمت در میلیون', 'pageStart' => 95, 'pageEnd' => 97],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'مولار', 'pageStart' => 98, 'pageEnd' => 99],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'آیا نمک ها به یک اندازه در آب حل می شوند؟', 'pageStart' => 100, 'pageEnd' => 103],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'رفتار آب و دیگر مولکول ها در میدان الکتریکی', 'pageStart' => 104, 'pageEnd' => 105],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'نیروهای بین مولکولی آب', 'pageStart' => 106, 'pageEnd' => 107],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'پیوند های هیدروژنی در حالت های فیزیکی گوناگون', 'pageStart' => 108, 'pageEnd' => 108],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'آب و دیگر حلال ها', 'pageStart' => 109, 'pageEnd' => 110],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'کدام مواد با یکدیگر محلول می سازند؟', 'pageStart' => 111, 'pageEnd' => 111],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'فرآیند انحلال نمک ها در آب', 'pageStart' => 112, 'pageEnd' => 112],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'آیا گاز ها هم در آب حل می شوند؟', 'pageStart' => 113, 'pageEnd' => 115],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'رد پای آب در زندگی', 'pageStart' => 116, 'pageEnd' => 119],
            ['course_id' => 5, 'season' => 'فصل ۳ آب آهنگ زندگی', 'content' => 'تمرین دوره ای', 'pageStart' => 120, 'pageEnd' => 122],

        ]);
    }
}
